import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import { useAppDispatch, useAppSelector } from '~redux/hooks';
import { logIn } from '~redux/modules/user';

import { IUser } from '~types/entities';
import Link from 'next/link';

const Home: NextPage = () => {
  const { userData } = useAppSelector(state => state.user);

  const [email, setEmail] = useState<string>('');
  const dispatch = useAppDispatch();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const userInfo: IUser = { email };

    dispatch(logIn(userInfo));
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>): void =>
    setEmail(e.target.value);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        {JSON.stringify(userData)}
        <form onSubmit={handleSubmit}>
          <input
            // type="email"
            placeholder="Email"
            value={email}
            onChange={handleInputChange}
          />
          <button type="submit">Submit</button>
        </form>
        <Link href="/odessa">Odessa</Link>
      </main>
    </div>
  );
};

export default Home;
